version: "3.8"

services:
  pomapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000"
    networks:
      - vue

  httpnewserver:
    build:
      context: ./nginxconf
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks:
      - vue
    depends_on:
      - pomapp

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
    networks:
      - vue

networks:
  vue: